# Generated by NodesO₃ v0.1.0 (https://github.com/LeviLovie/NodesO3)

def panic(msg: str) -> None:
    raise RuntimeError(f"PANIC: {msg}")

# Node Const#3
output_3_0 = 5.5

# Node Const#4
output_4_0 = 6

# Node Add#2
if "[Int, Float]" != "[Int, Float]":
  panic("Add#2: Type mismatch: [Int, Float] vs [Int, Float]")
output_2_0 = output_3_0 + output_4_0

# Node Add#1
if "[Int, Float]" != "[Int, Float]":
  panic("Add#1: Type mismatch: [Int, Float] vs [Int, Float]")
output_1_0 = output_3_0 + output_2_0

# Node Print#0
print(output_1_0)

