# Generated by NodesO₃ v0.1.0 (https://github.com/LeviLovie/NodesO3)

def panic(msg: str) -> None:
    raise RuntimeError(f"PANIC: {msg}")

output_1_0 = 5.5
output_4_0 = 5.5
if "[Int, Float]" != "[Int, Float]":
  panic("Add#3: Type mismatch: [Int, Float] vs [Int, Float]")
output_3_0 = output_1_0 + output_4_0
if "[Int, Float]" != "[Int, Float]":
  panic("Add#0: Type mismatch: [Int, Float] vs [Int, Float]")
output_0_0 = output_1_0 + output_3_0
print(output_0_0)
