use anyhow::{bail, Context, Result};

use crate::compiler::{IOMap, NodeMap, UpstreamTraversal};

const SYS_MODULE: &str = include_str!("../python/sys.py");

pub fn write(
    debug_info: bool,
    node_map: NodeMap,
    io_map: IOMap,
    traversal: UpstreamTraversal,
) -> Result<String> {
    let exec_order = traversal.execution_order();
    let mut output = String::new();
    output.push_str(&format!(
        "# Generated by NodesO₃ v{} (https://github.com/LeviLovie/NodesO3)\n\n",
        env!("CARGO_PKG_VERSION")
    ));

    output.push_str(SYS_MODULE);
    output.push('\n');

    for node_id in exec_order {
        if let Some(node) = node_map.get(*node_id) {
            let node_output = write_node(debug_info, node, &node_map, &io_map)
                .context(format!("Failed to write node {}", node.id))?;
            output.push_str(&node_output)
        } else {
            bail!("Node ID {} not found in NodeMap", node_id);
        }
    }

    Ok(output)
}

fn write_node(
    debug_info: bool,
    node: &crate::graph::Node,
    node_map: &NodeMap,
    io_map: &IOMap,
) -> Result<String> {
    let mut output = String::new();
    if debug_info {
        output.push_str(&format!("# Node {}#{}\n", node.desc.title, node.id));
    }

    let mut py_impl = node.desc.py_impl.trim().trim_end_matches("\n").to_string();
    replace(
        &mut py_impl,
        "{title}".to_string(),
        node.desc.title.to_string(),
    );
    replace(&mut py_impl, "{id}".to_string(), node.id.to_string());

    for field in &node.desc.fields {
        replace(
            &mut py_impl,
            format!("{{f_{}}}", field.name),
            field.value.to_string(),
        );
    }

    for (i, input) in node.desc.inputs.iter().enumerate() {
        if let Some(&(from_node, from_port)) = io_map.get((node.id, i)) {
            let type_str = if let Some(from_node) = node_map.get(from_node) {
                if let Some(from_port) = from_node.desc.outputs.get(from_port) {
                    from_port.data_type.to_string()
                } else {
                    bail!(
                        "Output port {} of node {} not found",
                        from_port,
                        from_node.id
                    );
                }
            } else {
                bail!("Node ID {} not found in NodeMap", from_node);
            };
            replace(&mut py_impl, format!("{{ti_{}}}", input.name), type_str);

            replace(
                &mut py_impl,
                format!("{{i_{}}}", input.name),
                format!("output_{}_{}", from_node, from_port),
            );
            continue;
        } else {
            bail!("Input {} of node {} is not connected", input.name, node.id);
        }
    }

    for (i, output) in node.desc.outputs.iter().enumerate() {
        replace(
            &mut py_impl,
            format!("{{o_{}}}", output.name),
            format!("output_{}_{}", node.id, i),
        );
    }

    output.push_str(&py_impl);
    output.push_str("\n");
    if debug_info {
        output.push_str("\n");
    }

    Ok(output)
}

fn replace(s: &mut String, from: String, to: String) {
    *s = s.replace(&from, &to);
}
